Repository FUSEEProjectTeam/Fusee, pull requests merged in 2020-11, with the labels that each got.

#270 .fus files with textures now load from subfolders. Fixes #202
  Examples/Complete/AdvancedUI/Desktop/Main.cs
  Examples/Complete/BoneAnimation/Desktop/Main.cs
  Examples/Complete/Camera/Desktop/Main.cs
  Examples/Complete/GeometryEditing/Desktop/Main.cs
  Examples/Complete/Materials/Desktop/Main.cs
  Examples/Complete/MeshingAround/Desktop/Main.cs
  Examples/Complete/NormalMap/Desktop/Main.cs
  Examples/Complete/Picking/Desktop/Main.cs
  Examples/Complete/Simple/Desktop/Main.cs
  Examples/Complete/SimpleDeferred/Desktop/Main.cs
  Examples/Complete/ThreeDFont/Desktop/Main.cs
  Examples/Complete/UI/Desktop/Main.cs
  src/Engine/Core/FusSceneConverter.cs
  src/Engine/Player/Desktop/Main.cs
  src/Serialization/FusFile.cs
  src/Tools/CmdLine/Verbs/Player.cs
Labels: bug

#277 Patch/color management
  Examples/Complete/AdvancedUI/Core/AdvancedUI.cs
  Examples/Complete/AdvancedUI/Core/UIHelper.cs
  Examples/Complete/BoneAnimation/Core/Bone.cs
  Examples/Complete/Camera/Core/Camera.cs
  Examples/Complete/GeometryEditing/Core/GeometryEditing.cs
  Examples/Complete/Integrations/Core/Main.cs
  Examples/Complete/Materials/Core/Materials.cs
  Examples/Complete/Picking/Core/Picking.cs
  Examples/Complete/RenderLayer/Core/Example.cs
  Examples/Complete/Simple/Core/Simple.cs
  Examples/Complete/SimpleDeferred/Core/SimpleDeferred.cs
  Examples/Complete/SurfaceEffects/Core/SurfaceEffects.cs
  Examples/Complete/ThreeDFont/Core/ThreeDFontHelper.cs
  Examples/Complete/UI/Core/UI.cs
  src/Base/Common/ColorUint.cs
  src/Engine/Core/Effects/Attributes.cs
  src/Engine/Core/Effects/SurfaceEffect.cs
  src/Engine/Core/FusSceneConverter.cs
  src/Engine/Core/MakeEffect.cs
  src/Engine/Core/RenderContext.cs
  src/Engine/Core/SceneRendererForward.cs
  src/Engine/Core/ShaderShards/Fragment/FragMain.cs
  src/Engine/Core/ShaderShards/Fragment/FragShards.cs
  src/Engine/Core/ShaderShards/Fragment/Lighting.cs
  src/Engine/GUI/Assets/text.frag
  src/Engine/GUI/Assets/texture.frag
  src/Engine/Imp/Graphics/Android/RenderContextImp.cs
  src/Engine/Player/Core/Player.cs
  src/Math/Core/M.cs
  src/Math/Core/float2.cs
  src/Math/Core/float3.cs
  src/Math/Core/float4.cs
  src/Tests/Math/Core/Float2Test.cs
  src/Tests/Math/Core/Float3Test.cs
  src/Tests/Math/Core/Float4Test.cs
  src/Tests/Math/Core/MTest.cs
  src/Tests/Serialization/Fusee.Serialization.Test/SimpleConvertSceneGraph.cs
Labels: enhancement, prio-must

#282 Patch/bunch of tiny fixes
  BuildNuget.cmd
  dis/DnTemplate/template/Fusee_App.csproj
  dis/VSTemplate/VSTemplate/Core/Core.csproj
  dis/VSTemplate/VSTemplate/Desktop/Desktop.csproj
  src/Base/Core/Diagnostics.cs
  src/Engine/Core/Audio.cs
  src/Engine/Core/Network.cs
  src/Engine/Core/Time.cs
  src/Engine/Imp/Graphics/Desktop/RenderContextImp.cs
  src/Engine/Imp/Graphics/Desktop/WindowsSpaceMouseDeviceImp.cs
  src/Tools/CmdLine/Verbs/Player.cs
Labels: bug, enhancement
