Repository FUSEEProjectTeam/Fusee, pull requests merged in 2021-09, with the labels that each got.

#335 Feature/UpdateIndependentRender
  dis/DnTemplate/template/Fusee_App.cs
  dis/VSTemplate/VSTemplate/Core/Core.cs
  src/Engine/Common/IRenderCanvasImp.cs
  src/Engine/Core/RenderCanvas.cs
  src/Engine/Core/Time.cs
  src/Engine/Imp/Graphics/Android/RenderCanvasImp.cs
  src/Engine/Imp/Graphics/Desktop/RenderCanvasImp.cs
  src/Engine/Player/Core/Player.cs
Labels: bug, enhancement, prio-must

#341 Remove shader src parameters from GUINode
  Examples/Complete/AdvancedUI/Core/AdvancedUI.cs
  Examples/Complete/AdvancedUI/Core/UIHelper.cs
  Examples/Complete/BoneAnimation/Core/Bone.cs
  Examples/Complete/Camera/Core/Camera.cs
  Examples/Complete/ComputeFractal/Core/ComputeFractal.cs
  Examples/Complete/Integrations/Core/Main.cs
  Examples/Complete/Labyrinth/Core/Labyrinth.cs
  Examples/Complete/Materials/Core/Materials.cs
  Examples/Complete/Picking/Core/Picking.cs
  Examples/Complete/Simple/Core/Simple.cs
  Examples/Complete/SimpleDeferred/Core/SimpleDeferred.cs
  Examples/Complete/Starkiller/Core/Starkiller.cs
  Examples/Complete/SurfaceEffects/Core/SurfaceEffects.cs
  Examples/Complete/UI/Core/UI.cs
  src/Engine/Core/FontMap.cs
  src/Engine/GUI/GUINode.cs
  src/Engine/Player/Core/Player.cs
Labels: prio-should

#342 Feature/RemoveSceneConverterNullId
  Examples/Complete/AdvancedUI/Android/MainActivity.cs
  Examples/Complete/BoneAnimation/Android/MainActivity.cs
  Examples/Complete/Camera/Android/MainActivity.cs
  Examples/Complete/GeometryEditing/Android/MainActivity.cs
  Examples/Complete/Integrations/Wpf/View/MainWindow.xaml.cs
  Examples/Complete/Labyrinth/Desktop/MainDesktop.cs
  Examples/Complete/Materials/Android/MainActivity.cs
  Examples/Complete/MeshingAround/Android/MainActivity.cs
  Examples/Complete/NormalMap/Android/MainActivity.cs
  Examples/Complete/Picking/Android/MainActivity.cs
  Examples/Complete/RenderLayer/Android/MainActivity.cs
  Examples/Complete/RenderLayer/Desktop/Main.cs
  Examples/Complete/Simple/Android/MainActivity.cs
  Examples/Complete/SimpleDeferred/Android/MainActivity.cs
  Examples/Complete/Starkiller/Desktop/MainDesktop.cs
  Examples/Complete/SurfaceEffects/Android/MainActivity.cs
  Examples/Complete/SurfaceEffects/Desktop/Main.cs
  Examples/Complete/ThreeDFont/Android/MainActivity.cs
  Examples/Complete/UI/Android/MainActivity.cs
  dis/VSTemplate/VSTemplate/Android/Android.cs
  dis/VSTemplate/VSTemplate/Desktop/Desktop.cs
  src/Engine/Core/FusSceneConverter.cs
  src/Engine/Player/Android/MainActivity.cs
  src/Tests/GameWindow/Desktop/Program.cs
  src/Tests/Render/Desktop/Program.cs
  src/Tests/Serialization/V1/SimpleConvertSceneGraph.cs
  src/Tools/FusViewer/MainWindowViewModel.cs
Labels: enhancement, inherited/legacy burdens
