Repository FUSEEProjectTeam/Fusee, pull requests merged in 2021-12, with the labels that each got.

#380 Feature/update components
  Examples/Complete/PointCloudLive/Core/PointCloudLive.cs
  src/Engine/Core/FusSceneConverter.cs
  src/Engine/Core/PrePassVisitor.cs
  src/Engine/Core/Scene/Camera.cs
  src/Engine/Core/Scene/Light.cs
  src/Engine/Core/Scene/Mesh.cs
  src/Engine/Core/Scene/SceneComponent.cs
  src/Engine/Core/ScenePicker.cs
  src/Engine/Core/SceneRendererDeferred.cs
  src/Engine/Core/SceneRendererForward.cs
  src/Engine/GUI/SceneInteractionHandler.cs
  src/Engine/Imp/Graphics/Desktop/DesktopRenderCanvasImpContext.cs
  src/Serialization/V1/FusCamera.cs
  src/Serialization/V1/FusComponent.cs
  src/Serialization/V1/FusLight.cs
  src/Tests/Xene/SimpleXene.cs
  src/Tools/BlenderScripts/addons/io_export_fus/BlenderVisitor.py
  src/Tools/BlenderScripts/addons/io_export_fus/FusSceneWriter.py
  src/Xene/IComponent.cs
  src/Xene/Visitor.cs
Labels: enhancement

#381 Feature/point cloud ooc surface effect
  Examples/Complete/Labyrinth/Desktop/Fusee.Examples.Labyrinth.Desktop.csproj
  Examples/Complete/PointCloudLive/Core/PointCloudLive.cs
  Examples/Complete/PointCloudOutOfCore/Core/PointCloudOutOfCore.cs
  Examples/Complete/PointCloudOutOfCore/Core/PtRenderParams.cs
  Examples/Complete/PointCloudOutOfCore/Wpf/MainWindow.xaml
  Examples/Complete/PointCloudOutOfCore/Wpf/MainWindow.xaml.cs
  src/Engine/Core/Effects/PointCloudSurfaceEffect.cs
  src/Engine/Core/RenderContext.cs
  src/Engine/Core/Scene/OctantD.cs
  src/Engine/Core/SceneRendererForward.cs
  src/Engine/Core/ShaderShards/Fragment/FragShards.cs
  src/Engine/Core/ShaderShards/UniformNameDeclarations.cs
  src/Engine/Core/ShaderShards/Vertex/VertMain.cs
  src/PointCloud/Common/IPtOctantLoader.cs
  src/PointCloud/Common/PointRenderEnums.cs
  src/PointCloud/OoCReaderWriter/PtOctantLoader.cs
  src/PointCloud/OoCReaderWriter/PtOctreeFileReader.cs
Labels: enhancement

#404 Feature/WasmWin
  .github/workflows/ci.yml
Labels: bug

#397 Feature/390 remove rc from pre pass visitor
  Examples/Complete/UI/Core/UI.cs
  src/Engine/Core/CameraResult.cs
  src/Engine/Core/LightResult.cs
  src/Engine/Core/PrePassVisitor.cs
  src/Engine/Core/ScenePicker.cs
  src/Engine/Core/SceneRendererDeferred.cs
  src/Engine/Core/SceneRendererForward.cs
Labels: prio-must
