Repository FUSEEProjectTeam/Fusee, pull requests merged in 2022-08, with the labels that each got.

#579 Feature/576 577 imgui filepicker improvements
  src/ImGui/Desktop/Fusee.ImGui.Desktop/Templates/ImGuiFilePicker.cs
Labels: bug, enhancement

#583 Fixed ImGuiController, use ImGui vtx and idx instead of self-written idx
  src/ImGui/Desktop/Fusee.ImGui.Desktop/ImGuiController.cs
Labels: bug

#592 Feature/WasmNuGetUpdate
  Examples/Complete/Camera/Blazor/Fusee.Examples.Camera.Blazor.csproj
  Examples/Complete/Deferred/Blazor/Fusee.Examples.Deferred.Blazor.csproj
  Examples/Complete/Picking/Blazor/Fusee.Examples.Picking.Blazor.csproj
  Examples/Complete/PickingRayCast/Blazor/Fusee.Examples.PickingRayCast.Blazor.csproj
  Examples/Complete/RenderContextOnly/Blazor/Fusee.Examples.RenderContextOnly.Blazor.csproj
  Examples/Complete/Simple/Blazor/Fusee.Examples.Simple.Blazor.csproj
  src/Base/Imp/Blazor/Fusee.Base.Imp.Blazor.csproj
  src/Engine/Imp/Graphics/Blazor/Fusee.Engine.Imp.Graphics.Blazor.csproj
  src/Engine/Player/Blazor/Fusee.Engine.Player.Blazor.csproj
Labels: dependencies

#599 Hotfix/fix nuget build
  .github/workflows/ci.yml
  dis/VSTemplate/VSIX/VSIX.csproj
Labels: bug

#598 Implement `LineRendering` and `LinePicking`
  src/Base/Core/FontImpBase.cs
  src/Engine/Core/Assets/line.frag
  src/Engine/Core/Assets/line.geom
  src/Engine/Core/Assets/line.vert
  src/Engine/Core/Fusee.Engine.Core.csproj
  src/Engine/Core/MakeEffect.cs
  src/Engine/Core/ScenePicker.cs
Labels: enhancement
