Repository FUSEEProjectTeam/Fusee, pull requests merged in 2022-10, with the labels that each got.

#649 Feature/647+648 diagnostics housekeeping
  src/Base/Core/Diagnostics.cs
Labels: enhancement, easy first contribution

#657 Added bool to determine pointcloud loading
  src/PointCloud/Potree/Potree2CloudDynamic.cs
Labels: enhancement

#654 Feature/652+653 fix line rendering
  src/Engine/Core/Scene/Mesh.cs
  src/Engine/Core/SceneRendererForward.cs
Labels: bug

#667 Scenepicker does not work with `WireframeCube`
  src/Engine/Core/ScenePicker.cs
Labels: bug

#669 ImGuiInput new implementation
  src/ImGui/Desktop/Fusee.ImGui.Desktop/ImGuiInputImp.cs
Labels: bug, enhancement
