Repository FUSEEProjectTeam/Fusee, pull requests merged in 2023-03, with the labels that each got.

#733 POL PotreeData and Reader updates
  Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2Core.cs
  src/PointCloud/Potree/V2/Data/PotreeData.cs
  src/PointCloud/Potree/V2/Potree2ReaderBase.cs
  src/PointCloud/Potree/V2/Potree2Writer.cs
  src/PointCloud/Potree/V2/Potree2WriterBase.cs
  src/PointCloud/Potree/V2/PotreeData.cs
Labels: enhancement

#731 Merge visualization points to a single point type.
  Examples/Complete/Picking/Desktop/Main.cs
  Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2.cs
  Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2Core.cs
  src/Base/Imp/Desktop/FileAssetProvider.cs
  src/Engine/Core/GpuMesh.cs
  src/Engine/Core/IPickerModule.cs
  src/Engine/Core/Scene/InstanceData.cs
  src/Engine/Core/SceneRayCaster.cs
  src/Engine/GUI/SceneInteractionHandler.cs
  src/Engine/Imp/Graphics/Desktop/RenderContextImp.cs
  src/PointCloud/Common/Assets/PointCloudInstanced.vert
  src/PointCloud/Common/Assets/PointDepthInstanced.frag
  src/PointCloud/Common/IPointReader.cs
  src/PointCloud/Common/IPointWriter.cs
  src/PointCloud/Common/PointTypes.cs
  src/PointCloud/Core/Fusee.PointCloud.Core.csproj
  src/PointCloud/Core/MeshMaker.cs
  src/PointCloud/Core/PointCloudDataHandler.cs
  src/PointCloud/Core/PointCloudOctant.cs
  src/PointCloud/Core/Scene/PointCloudComponent.cs
  src/PointCloud/Core/Scene/PointCloudPickerModule.cs
  src/PointCloud/Core/VisibilityTester.cs
  src/PointCloud/Core/VisualizationPoint.cs
  src/PointCloud/Potree/Potree2LAS.cs
  src/PointCloud/Potree/V2/Data/PotreePoint.cs
  src/PointCloud/Potree/V2/Potree2Reader.cs
  src/PointCloud/Potree/V2/Potree2ReaderBase.cs
  src/PointCloud/Potree/V2/Potree2Writer.cs
  src/PointCloud/Potree/V2/Potree2WriterBase.cs
  src/Serialization/V2/FusPickComponent.cs
Labels: prio-must

#719 Feature/NuGetUpdate
  ext/protobuf/Python/google/protobuf/__init__.py
  ext/protobuf/Python/google/protobuf/any_pb2.py
  ext/protobuf/Python/google/protobuf/api_pb2.py
  ext/protobuf/Python/google/protobuf/compiler/plugin_pb2.py
  ext/protobuf/Python/google/protobuf/descriptor.py
  ext/protobuf/Python/google/protobuf/descriptor_pb2.py
  ext/protobuf/Python/google/protobuf/descriptor_pool.py
  ext/protobuf/Python/google/protobuf/duration_pb2.py
  ext/protobuf/Python/google/protobuf/empty_pb2.py
  ext/protobuf/Python/google/protobuf/field_mask_pb2.py
  ext/protobuf/Python/google/protobuf/internal/__init__.py
  ext/protobuf/Python/google/protobuf/internal/_parameterized.py
  ext/protobuf/Python/google/protobuf/internal/api_implementation.py
  ext/protobuf/Python/google/protobuf/internal/decoder.py
  ext/protobuf/Python/google/protobuf/internal/descriptor_database_test.py
  ext/protobuf/Python/google/protobuf/internal/descriptor_pool_test.py
  ext/protobuf/Python/google/protobuf/internal/descriptor_test.py
  ext/protobuf/Python/google/protobuf/internal/extension_dict.py
  ext/protobuf/Python/google/protobuf/internal/field_mask.py
  ext/protobuf/Python/google/protobuf/internal/generator_test.py
  ext/protobuf/Python/google/protobuf/internal/import_test.py
  ext/protobuf/Python/google/protobuf/internal/import_test_package/__init__.py
  ext/protobuf/Python/google/protobuf/internal/json_format_test.py
  ext/protobuf/Python/google/protobuf/internal/keywords_test.py
  ext/protobuf/Python/google/protobuf/internal/message_factory_test.py
  ext/protobuf/Python/google/protobuf/internal/message_test.py
  ext/protobuf/Python/google/protobuf/internal/proto_builder_test.py
  ext/protobuf/Python/google/protobuf/internal/python_message.py
  ext/protobuf/Python/google/protobuf/internal/reflection_test.py
  ext/protobuf/Python/google/protobuf/internal/service_reflection_test.py
  ext/protobuf/Python/google/protobuf/internal/symbol_database_test.py
  ext/protobuf/Python/google/protobuf/internal/test_util.py
  ext/protobuf/Python/google/protobuf/internal/text_encoding_test.py
  ext/protobuf/Python/google/protobuf/internal/text_format_test.py
  ext/protobuf/Python/google/protobuf/internal/type_checkers.py
  ext/protobuf/Python/google/protobuf/internal/unknown_fields_test.py
  ext/protobuf/Python/google/protobuf/internal/well_known_types.py
  ext/protobuf/Python/google/protobuf/internal/well_known_types_test.py
  ext/protobuf/Python/google/protobuf/internal/wire_format.py
  ext/protobuf/Python/google/protobuf/internal/wire_format_test.py
  ext/protobuf/Python/google/protobuf/json_format.py
  ext/protobuf/Python/google/protobuf/message.py
  ext/protobuf/Python/google/protobuf/message_factory.py
  ext/protobuf/Python/google/protobuf/proto_builder.py
  ext/protobuf/Python/google/protobuf/reflection.py
  ext/protobuf/Python/google/protobuf/source_context_pb2.py
  ext/protobuf/Python/google/protobuf/struct_pb2.py
  ext/protobuf/Python/google/protobuf/symbol_database.py
  ext/protobuf/Python/google/protobuf/text_encoding.py
  ext/protobuf/Python/google/protobuf/text_format.py
  ext/protobuf/Python/google/protobuf/timestamp_pb2.py
  ext/protobuf/Python/google/protobuf/type_pb2.py
  ext/protobuf/Python/google/protobuf/wrappers_pb2.py
  ext/protobuf/Python/six.py
  src/Engine/Imp/Graphics/Desktop/Fusee.Engine.Imp.Graphics.Desktop.csproj
  src/Tests/Render/Desktop/Fusee.Tests.Render.Desktop.csproj
  src/Tools/BlenderScripts/addons/io_export_fus/requirements.txt
  src/Tools/CmdLine/Fusee.Tools.CmdLine.csproj
Labels: dependencies

#725 Point cloud picking
  Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2.cs
  Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2Core.cs
  Examples/Complete/PointCloudPotree2/ImGui/PointCloudRenderingControl.cs
  src/Engine/Core/Primitives/Plane.cs
  src/Engine/Core/Primitives/Sphere.cs
  src/Engine/Core/ScenePicker.cs
  src/ImGui/Desktop/Fusee.ImGui.Desktop/Templates/ImGuiFilePicker.cs
  src/PointCloud/Core/Scene/PointCloudPickerModule.cs
  src/Tests/Render/Desktop/References/AdvancedUI.png
  src/Tests/Render/Desktop/References/Camera.png
  src/Tests/Render/Desktop/References/Deferred.png
  src/Tests/Render/Desktop/References/Fractal.png
  src/Tests/Render/Desktop/References/Labyrinth.png
  src/Tests/Render/Desktop/References/Materials.png
  src/Tests/Render/Desktop/References/Picking.png
  src/Tests/Render/Desktop/References/PointCloudPotree2.png
  src/Tests/Render/Desktop/References/Simple.png
  src/Tests/Render/Desktop/References/ThreeDFont.png
  src/Xene/Visitor.cs
Labels: enhancement, prio-must

#715 F.Math.Core JSON serialization
  src/Math/Core/AABBd.cs
  src/Math/Core/AABBf.cs
  src/Math/Core/Curve.cs
  src/Math/Core/Eigen.cs
  src/Math/Core/FrustumD.cs
  src/Math/Core/FrustumF.cs
  src/Math/Core/MinMaxRect.cs
  src/Math/Core/OBBd.cs
  src/Math/Core/OBBf.cs
  src/Math/Core/PlaneD.cs
  src/Math/Core/PlaneF.cs
  src/Math/Core/QuaternionD.cs
  src/Math/Core/QuaternionF.cs
  src/Math/Core/Rayd.cs
  src/Math/Core/Rayf.cs
  src/Math/Core/double2.cs
  src/Math/Core/double3.cs
  src/Math/Core/double3x3.cs
  src/Math/Core/double4.cs
  src/Math/Core/double4x4.cs
  src/Math/Core/float2.cs
  src/Math/Core/float3x3.cs
  src/Math/Core/int2.cs
  src/Math/Core/int3.cs
  src/Math/Core/int4.cs
Labels: enhancement
